import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execa } from 'execa';
import readline from 'node:readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface InitOptions {
  framework: 'vite' | 'next' | 'cra' | 'static';
  packaging: 'capacitor' | 'tauri' | 'twa';
  firebase?: boolean;
  firebaseProjectId?: string;
  firebaseApiKey?: string;
  allPlugins?: boolean;
  force?: boolean;
  appName?: string;
  appId?: string;
  description?: string;
  authorName?: string;
  authorEmail?: string;
  assetsSource?: string;
}

interface PackageManagerProfile {
  name: 'npm' | 'pnpm' | 'yarn' | 'bun';
  installCommand: string;
  installArgs: string[];
  runBuildCommand: string;
}

interface AppMetadata {
  appName: string;
  appId: string;
  description: string;
  authorName: string;
  authorEmail: string;
  assetsSource: string;
}

export async function initProject(options: InitOptions): Promise<void> {
  const cwd = process.cwd();
  const packageManager = detectPackageManager(cwd);
  const configPath = path.join(cwd, 'deploid.config.ts');
  const configExists = fs.existsSync(configPath);
  const webDir = getWebDir(options.framework);

  if (options.packaging !== 'capacitor') {
    throw new Error(`Packaging engine "${options.packaging}" is not supported in Deploid 2.0. Use "capacitor".`);
  }

  let metadata: AppMetadata | null = null;

  if (configExists && !options.force) {
    console.log('⚠️  deploid.config.ts already exists. Continuing in retry mode.');
    console.log('Use --force to regenerate deploid.config.ts.');
  } else {
    metadata = await collectAppMetadata(cwd, options);

    // If no Firebase options provided, ask interactively
    if (options.packaging === 'capacitor' && options.firebase === undefined) {
      const firebaseSetup = await askFirebaseSetup();
      options.firebase = firebaseSetup.enabled;
      options.firebaseProjectId = firebaseSetup.projectId;
      options.firebaseApiKey = firebaseSetup.apiKey;
    }

    // Generate config based on options
    const config = generateConfig(options, packageManager, metadata);

    // Write config file
    fs.writeFileSync(configPath, config);
    if (configExists && options.force) {
      console.log('✅ Recreated deploid.config.ts');
    } else {
      console.log('✅ Created deploid.config.ts');
    }

    updatePackageJsonMetadata(cwd, metadata, webDir);
  }

  // Create basic project structure
  await createProjectStructure(cwd, options);
  
  // Install required dependencies
  await installDependencies(cwd, options, packageManager);
  
  // Setup Firebase if requested (skip during retry unless explicitly requested)
  if (options.firebase && options.packaging === 'capacitor') {
    await setupFirebase(cwd, options);
  }
  
  // Install plugin dependencies
  console.log('📦 Installing plugin dependencies...');
  await installPluginDependencies(cwd, options, packageManager);
  
  console.log('🎉 Deploid initialized!');
  console.log('Next steps:');
  console.log('  1. Add your logo to assets/logo.svg');
  console.log('  2. Run: deploid assets');
  console.log('  3. Run: deploid package');
}

function generateConfig(options: InitOptions, packageManager: PackageManagerProfile, metadata: AppMetadata): string {
  const { framework, packaging, firebase, firebaseProjectId } = options;
  
  const buildCommand = getBuildCommand(framework, packageManager);
  const webDir = getWebDir(framework);
  
  const firebaseConfig = firebase ? `
  firebase: {
    projectId: '${firebaseProjectId || 'your-firebase-project-id'}',
    enabled: true,
  },` : '';
  
  return `// Deploid configuration
// Generated by deploid init

export default {
  appName: '${metadata.appName}',
  appId: '${metadata.appId}',
  web: {
    framework: '${framework}',
    buildCommand: '${buildCommand}',
    webDir: '${webDir}',
    pwa: { manifest: 'public/manifest.json', serviceWorker: true },
  },
  android: {
    packaging: '${packaging}',
    targetSdk: 34,
    minSdk: 24,
    permissions: ['INTERNET'],
    version: { code: 1, name: '1.0.0' },
    display: {
      fullscreen: false,
      orientation: 'portrait',
      statusBarStyle: 'auto',
      windowSoftInputMode: 'adjustResize',
    },
    build: {
      minifyEnabled: false,
      enableMultidex: false,
    },
  },${firebaseConfig}
  assets: {
    source: '${metadata.assetsSource}',
    output: 'assets-gen/',
  },
  publish: {
    github: { repo: 'your-username/your-repo', draft: true },
  },
};
`;
}

function getBuildCommand(framework: string, packageManager: PackageManagerProfile): string {
  const buildCommand = packageManager.runBuildCommand;
  switch (framework) {
    case 'vite': return buildCommand;
    case 'next': return buildCommand;
    case 'cra': return buildCommand;
    case 'static': return 'echo "Static files ready"';
    default: return buildCommand;
  }
}

function getWebDir(framework: string): string {
  switch (framework) {
    case 'vite': return 'dist';
    case 'next': return 'out';
    case 'cra': return 'build';
    case 'static': return 'public';
    default: return 'dist';
  }
}

async function createProjectStructure(cwd: string, options: InitOptions): Promise<void> {
  // Create assets directory
  const assetsDir = path.join(cwd, 'assets');
  if (!fs.existsSync(assetsDir)) {
    fs.mkdirSync(assetsDir, { recursive: true });
    console.log('✅ Created assets/ directory');
  }

  // Create assets-gen directory
  const assetsGenDir = path.join(cwd, 'assets-gen');
  if (!fs.existsSync(assetsGenDir)) {
    fs.mkdirSync(assetsGenDir, { recursive: true });
    console.log('✅ Created assets-gen/ directory');
  }

  // Create template files based on packaging engine
  await createTemplateFiles(cwd, options.packaging, options.framework, metadataFromOptions(options));
}

function detectPackageManager(cwd: string): PackageManagerProfile {
  if (fs.existsSync(path.join(cwd, 'pnpm-lock.yaml'))) {
    return {
      name: 'pnpm',
      installCommand: 'pnpm',
      installArgs: ['add'],
      runBuildCommand: 'pnpm run build'
    };
  }

  if (fs.existsSync(path.join(cwd, 'yarn.lock'))) {
    return {
      name: 'yarn',
      installCommand: 'yarn',
      installArgs: ['add'],
      runBuildCommand: 'yarn build'
    };
  }

  if (fs.existsSync(path.join(cwd, 'bun.lockb')) || fs.existsSync(path.join(cwd, 'bun.lock'))) {
    return {
      name: 'bun',
      installCommand: 'bun',
      installArgs: ['add'],
      runBuildCommand: 'bun run build'
    };
  }

  return {
    name: 'npm',
    installCommand: 'npm',
    installArgs: ['install'],
    runBuildCommand: 'npm run build'
  };
}

function installPackages(
  cwd: string,
  packageManager: PackageManagerProfile,
  packages: string[]
) {
  return execa(packageManager.installCommand, [...packageManager.installArgs, ...packages], {
    cwd,
    stdio: 'inherit'
  });
}

function installCommandHint(packageManager: PackageManagerProfile, packages: string[]): string {
  return `${packageManager.installCommand} ${[...packageManager.installArgs, ...packages].join(' ')}`;
}

async function installDependencies(cwd: string, options: InitOptions, packageManager: PackageManagerProfile): Promise<void> {
  console.log('📦 Installing required dependencies...');
  console.log(`Using package manager: ${packageManager.name}`);
  
  try {
    // Install Capacitor CLI and core packages
    await installPackages(cwd, packageManager, ['@capacitor/cli', '@capacitor/core']);
    
    // Install platform-specific packages based on packaging engine
    switch (options.packaging) {
      case 'capacitor':
        await installPackages(cwd, packageManager, ['@capacitor/android']);
        break;
      case 'tauri':
        // TODO: Install Tauri dependencies
        console.log('⚠️  Tauri packaging not yet implemented');
        break;
      case 'twa':
        // TODO: Install TWA dependencies
        console.log('⚠️  TWA packaging not yet implemented');
        break;
    }
    
    console.log('✅ Dependencies installed');
  } catch (error) {
    console.log('⚠️  Failed to install dependencies automatically');
    console.log('Please run manually:');
    console.log(`  ${installCommandHint(packageManager, ['@capacitor/cli', '@capacitor/core', '@capacitor/android'])}`);
  }
}

function metadataFromOptions(options: InitOptions): AppMetadata {
  return {
    appName: options.appName || 'MyApp',
    appId: options.appId || 'com.example.myapp',
    description: options.description || 'Built with Deploid',
    authorName: options.authorName || 'Your Name',
    authorEmail: options.authorEmail || 'you@example.com',
    assetsSource: options.assetsSource || 'assets/logo.svg'
  };
}

function inferAppId(appName: string): string {
  const cleaned = appName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '.')
    .replace(/^\.+|\.+$/g, '')
    .replace(/\.{2,}/g, '.');
  return `com.example.${cleaned || 'myapp'}`;
}

async function collectAppMetadata(cwd: string, options: InitOptions): Promise<AppMetadata> {
  const packageJsonPath = path.join(cwd, 'package.json');
  let packageJson: any = {};
  if (fs.existsSync(packageJsonPath)) {
    try {
      packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    } catch {
      packageJson = {};
    }
  }

  const pkgAuthorName =
    typeof packageJson.author === 'string'
      ? packageJson.author
      : packageJson.author?.name;
  const pkgAuthorEmail =
    typeof packageJson.author === 'object'
      ? packageJson.author?.email
      : undefined;
  const packageName = typeof packageJson.name === 'string' ? packageJson.name : 'myapp';

  const defaults: AppMetadata = {
    appName: options.appName || packageJson.productName || packageJson.appName || 'MyApp',
    appId: options.appId || inferAppId(options.appName || packageName),
    description: options.description || packageJson.description || 'Built with Deploid',
    authorName: options.authorName || pkgAuthorName || 'Your Name',
    authorEmail: options.authorEmail || pkgAuthorEmail || 'you@example.com',
    assetsSource: options.assetsSource || 'assets/logo.svg'
  };

  const shouldPrompt =
    !options.appName &&
    !options.appId &&
    !options.description &&
    !options.authorName &&
    !options.authorEmail &&
    !options.assetsSource;

  if (!shouldPrompt) {
    options.appName = defaults.appName;
    options.appId = defaults.appId;
    options.description = defaults.description;
    options.authorName = defaults.authorName;
    options.authorEmail = defaults.authorEmail;
    options.assetsSource = defaults.assetsSource;
    return defaults;
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const question = (prompt: string): Promise<string> => new Promise((resolve) => rl.question(prompt, resolve));

  try {
    console.log('\n🧾 Project metadata');
    const appNameInput = (await question(`App name [${defaults.appName}]: `)).trim();
    const appName = appNameInput || defaults.appName;

    const inferredAppId = inferAppId(appName);
    const appIdDefault = options.appId || inferredAppId || defaults.appId;
    const appIdInput = (await question(`App ID (reverse domain) [${appIdDefault}]: `)).trim();
    const appId = appIdInput || appIdDefault;

    const descriptionInput = (await question(`Description [${defaults.description}]: `)).trim();
    const description = descriptionInput || defaults.description;

    const authorNameInput = (await question(`Author name [${defaults.authorName}]: `)).trim();
    const authorName = authorNameInput || defaults.authorName;

    const authorEmailInput = (await question(`Author email [${defaults.authorEmail}]: `)).trim();
    const authorEmail = authorEmailInput || defaults.authorEmail;

    const assetsSourceInput = (await question(`Asset source path [${defaults.assetsSource}]: `)).trim();
    const assetsSource = assetsSourceInput || defaults.assetsSource;

    const metadata = { appName, appId, description, authorName, authorEmail, assetsSource };
    options.appName = metadata.appName;
    options.appId = metadata.appId;
    options.description = metadata.description;
    options.authorName = metadata.authorName;
    options.authorEmail = metadata.authorEmail;
    options.assetsSource = metadata.assetsSource;
    return metadata;
  } finally {
    rl.close();
  }
}

function updatePackageJsonMetadata(cwd: string, metadata: AppMetadata, webDir: string): void {
  const packageJsonPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(packageJsonPath)) return;

  let packageJson: any;
  try {
    packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  } catch {
    return;
  }

  packageJson.description = metadata.description;
  packageJson.author = {
    name: metadata.authorName,
    email: metadata.authorEmail
  };
  packageJson.main ||= 'electron/main.cjs';

  packageJson.build ||= {};
  packageJson.build.appId ||= metadata.appId;
  packageJson.build.productName ||= metadata.appName;
  packageJson.build.directories ||= {};
  packageJson.build.directories.output ||= 'dist-electron';
  packageJson.build.linux ||= {};
  packageJson.build.linux.maintainer ||= `${metadata.authorName} <${metadata.authorEmail}>`;
  packageJson.build.linux.category ||= 'Utility';
  packageJson.build.icon ||= metadata.assetsSource;
  packageJson.build.files ||= [`${webDir}/**/*`, 'electron/**/*', 'package.json'];

  fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);
  console.log('✅ Updated package.json metadata');
}

async function createTemplateFiles(cwd: string, packaging: string, framework: string, metadata: AppMetadata): Promise<void> {
  const templatesDir = path.join(__dirname, '../../templates');
  const webDir = getWebDir(framework);
  
  switch (packaging) {
    case 'capacitor':
      await createCapacitorTemplate(cwd, metadata, webDir);
      break;
    case 'tauri':
      await createTauriTemplate(cwd, metadata);
      break;
    case 'twa':
      await createTWATemplate(cwd, metadata);
      break;
  }
}

async function createCapacitorTemplate(cwd: string, metadata: AppMetadata, webDir: string): Promise<void> {
  const capacitorConfig = `{
  "appId": "${metadata.appId}",
  "appName": "${metadata.appName}",
  "webDir": "${webDir}",
  "bundledWebRuntime": false,
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 2000
    }
  }
}`;

  fs.writeFileSync(path.join(cwd, 'capacitor.config.json'), capacitorConfig);
  console.log('✅ Created capacitor.config.json');
}

async function createTauriTemplate(cwd: string, metadata: AppMetadata): Promise<void> {
  const tauriDir = path.join(cwd, 'src-tauri');
  if (!fs.existsSync(tauriDir)) {
    fs.mkdirSync(tauriDir, { recursive: true });
  }

  const tauriConfig = `{
  "build": {
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build",
    "devPath": "http://localhost:3000",
    "distDir": "../dist"
  },
  "package": {
    "productName": "${metadata.appName}",
    "version": "1.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "${metadata.appId}",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "${metadata.appName}",
        "width": 1200,
        "height": 800
      }
    ]
  }
}`;

  fs.writeFileSync(path.join(tauriDir, 'tauri.conf.json'), tauriConfig);
  console.log('✅ Created tauri.conf.json');
}

async function createTWATemplate(cwd: string, metadata: AppMetadata): Promise<void> {
  const publicDir = path.join(cwd, 'public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const manifest = `{
  "name": "${metadata.appName}",
  "short_name": "${metadata.appName}",
  "description": "${metadata.description}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#000000",
  "icons": [
    {
      "src": "assets-gen/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets-gen/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}`;

  fs.writeFileSync(path.join(publicDir, 'manifest.json'), manifest);
  console.log('✅ Created public/manifest.json');
}

async function askFirebaseSetup(): Promise<{ enabled: boolean; projectId?: string; apiKey?: string }> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const question = (prompt: string): Promise<string> => {
    return new Promise((resolve) => {
      rl.question(prompt, resolve);
    });
  };

  try {
    console.log('\n🔥 Firebase Setup for Push Notifications');
    console.log('Firebase enables native push notifications for your Android app.');
    
    const enableFirebase = await question('Do you want to set up Firebase for push notifications? (y/N): ');
    const enabled = enableFirebase.toLowerCase().startsWith('y');
    
    if (!enabled) {
      console.log('⚠️  Skipping Firebase setup. You can add it later with: deploid firebase');
      return { enabled: false };
    }

    console.log('\n📋 Firebase Setup Options:');
    console.log('1. Auto-create Firebase project (requires Firebase CLI)');
    console.log('2. Use existing Firebase project');
    console.log('3. Skip for now (add later with: deploid firebase)');
    
    const choice = await question('Choose an option (1-3): ');
    
    if (choice === '3') {
      console.log('⚠️  Skipping Firebase setup. You can add it later with: deploid firebase');
      return { enabled: false };
    }
    
    if (choice === '1') {
      console.log('🚀 Auto-creating Firebase project...');
      return { enabled: true };
    }
    
    if (choice === '2') {
      const projectId = await question('Enter your Firebase project ID: ');
      const apiKey = await question('Enter your Firebase API key (optional): ');
      return { enabled: true, projectId, apiKey };
    }
    
    return { enabled: false };
  } finally {
    rl.close();
  }
}

async function setupFirebase(cwd: string, options: InitOptions): Promise<void> {
  console.log('🔥 Setting up Firebase...');
  
  try {
    // Check if Firebase CLI is installed
    try {
      await execa('firebase', ['--version'], { stdio: 'pipe' });
    } catch (error) {
      console.log('📦 Installing Firebase CLI...');
      await execa('npm', ['install', '-g', 'firebase-tools'], { stdio: 'inherit' });
    }
    
    // Login to Firebase
    console.log('🔐 Please login to Firebase...');
    await execa('firebase', ['login'], { stdio: 'inherit' });
    
    // Create Firebase project
    if (!options.firebaseProjectId) {
      console.log('🚀 Creating Firebase project...');
      const projectName = path.basename(cwd).replace(/[^a-zA-Z0-9]/g, '-');
      await execa('firebase', ['projects:create', projectName], { stdio: 'inherit' });
      options.firebaseProjectId = projectName;
    }
    
    // Initialize Firebase in the project
    await execa('firebase', ['init', 'hosting'], { 
      cwd, 
      stdio: 'inherit',
      input: 'y\nn\n' // Yes to hosting, no to other features
    });
    
    // Add Android app to Firebase
    console.log('📱 Adding Android app to Firebase...');
    const packageName = options.appId || 'com.example.myapp';
    await execa('firebase', ['apps:create', 'android', packageName], { 
      cwd, 
      stdio: 'inherit' 
    });
    
    // Download google-services.json
    console.log('📄 Downloading google-services.json...');
    await execa('firebase', ['apps:sdkconfig', 'android'], { 
      cwd, 
      stdio: 'inherit' 
    });
    
    // Move google-services.json to correct location
    const sourcePath = path.join(cwd, 'google-services.json');
    const targetPath = path.join(cwd, 'android/app/google-services.json');
    
    if (fs.existsSync(sourcePath)) {
      fs.copyFileSync(sourcePath, targetPath);
      fs.unlinkSync(sourcePath); // Remove from root
      console.log('✅ Firebase setup complete!');
    } else {
      console.log('⚠️  google-services.json not found. Please download it manually from Firebase Console.');
    }
    
  } catch (error) {
    console.log('⚠️  Firebase setup failed:', error);
    console.log('You can set it up manually later with: deploid firebase');
  }
}

async function installPluginDependencies(cwd: string, options: InitOptions, packageManager: PackageManagerProfile): Promise<void> {
  try {
    // Define available plugins
    const availablePlugins = {
      'assets': {
        name: '@deploid/plugin-assets',
        description: 'Generate app icons and assets from your logo',
        required: true // Always needed for basic functionality
      },
      'packaging-capacitor': {
        name: '@deploid/plugin-packaging-capacitor',
        description: 'Package your app with Capacitor',
        required: options.packaging === 'capacitor'
      },
      'packaging-electron': {
        name: '@deploid/plugin-packaging-electron',
        description: 'Create Electron desktop apps for Windows, macOS, and Linux',
        required: false
      },
      'build-android': {
        name: '@deploid/plugin-build-android',
        description: 'Build Android APK/AAB files',
        required: true // Always needed for Android builds
      },
      'deploy-android': {
        name: '@deploid/plugin-deploy-android',
        description: 'Deploy to Android devices via ADB',
        required: false
      },
      'prepare-ios': {
        name: '@deploid/plugin-prepare-ios',
        description: 'Prepare iOS project for Mac handoff',
        required: false
      },
      'debug-network': {
        name: '@deploid/plugin-debug-network',
        description: 'Add network debugging tools to your app',
        required: false
      },
      'storage': {
        name: '@deploid/plugin-storage',
        description: 'Cross-platform storage utilities for web and native',
        required: false
      }
    };

    const requiredPlugins: string[] = [];
    const optionalPlugins: string[] = [];
    
    // Add required plugins
    for (const [key, plugin] of Object.entries(availablePlugins)) {
      if (plugin.required) {
        requiredPlugins.push(plugin.name);
        console.log(`✅ ${plugin.description} (required)`);
      }
    }

    // Ask about optional plugins
    if (options.allPlugins) {
      console.log('\n🔧 Installing all optional plugins...');
      for (const [key, plugin] of Object.entries(availablePlugins)) {
        if (!plugin.required) {
          optionalPlugins.push(plugin.name);
          console.log(`✅ ${plugin.description}`);
        }
      }
    } else {
      console.log('\n🔧 Optional plugins:');
      for (const [key, plugin] of Object.entries(availablePlugins)) {
        if (!plugin.required) {
          const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
          });
          
          const answer = await new Promise<string>((resolve) => {
            rl.question(`Install ${plugin.description}? (y/N): `, resolve);
          });
          rl.close();
          
          if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
            optionalPlugins.push(plugin.name);
            console.log(`✅ ${plugin.description}`);
          } else {
            console.log(`⏭️  Skipped ${plugin.description}`);
          }
        }
      }
    }
    
    if (requiredPlugins.length === 0 && optionalPlugins.length === 0) {
      console.log(`⚠️  No plugins selected. You can install them later with: ${installCommandHint(packageManager, ['<plugin-name>'])}`);
      return;
    }

    if (requiredPlugins.length > 0) {
      console.log(`\n📦 Installing required plugins: ${requiredPlugins.join(', ')}`);
      await installPackages(cwd, packageManager, requiredPlugins);
      console.log('✅ Required plugin packages installed');
    }

    if (optionalPlugins.length > 0) {
      console.log(`\n📦 Installing optional plugins: ${optionalPlugins.join(', ')}`);
      try {
        await installPackages(cwd, packageManager, optionalPlugins);
        console.log('✅ Optional plugin packages installed');
      } catch (error) {
        console.log('⚠️  Failed to install one or more optional plugin packages:', error);
        console.log(`Required plugins are installed. You can add optional plugins manually later with: ${installCommandHint(packageManager, ['<plugin-name>'])}`);
      }
    }
  } catch (error) {
    console.log('⚠️  Failed to install plugin packages:', error);
    console.log(`You can install them manually later with: ${installCommandHint(packageManager, ['<plugin-name>'])}`);
  }
}
